
export const DISPLAY_ALERT= "SHOW_ALERT"
export const CLEAR_ALERT= "CLEAR_ALERT"
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"
export const CLOSE_DROPDOWN_OVERLY = "CLOSE_DROPDOWN_OVERLY"
// export const OPEN_MENU = "OPEN_MENU"

export const TOGGLE_DROPDOWN = "TOGGLE_DROPDOWN"
export const TOGGLE_OVERLY = "TOGGLE_OVERLY"

export const LOGOUT_USER = "LOGOUT_USER"
export const SHOW_SIDEBAR = 'SHOW_SIDEBAR'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HIDE_RECOMMENDATIONS = 'HIDE_RECOMMENDATIONS'
export const DISPLAY_RECOMMENDATIONS = 'DISPLAY_RECOMMENDATIONS'

export const UPLOAD_REDOO_BEGIN = 'UPLOAD_REDOO_BEGIN'
export const UPLOAD_REDOO_SUCCESS = 'UPLOAD_REDOO_SUCCESS'
export const UPLOAD_REDOO_ERROR = 'UPLOAD_REDOO_ERROR'

export const UPLOAD_VIDEO_BEGIN = 'UPLOAD_VIDEO_BEGIN'
export const UPLOAD_VIDEO_SUCCESS = 'UPLOAD_VIDEO_SUCCESS'
export const UPLOAD_VIDEO_ERROR = 'UPLOAD_VIDEO_ERROR'

export const GET_REDOOS_BEGIN ="GET_REDOOS_BEGIN "
export const GET_REDOOS_SUCCESS =" GET_REDOOS_SUCCESS "

export const GET_VIDEOS_BEGIN = "GET_VIDEOS_BEGIN"
export const GET_VIDEOS_SUCCESS = "GET_VIDEOS_SUCCESS"
export const GET_VIDEO_BEGIN = "GET_VIDEO_BEGIN"
export const GET_VIDEO_SUCCESS = "GET_VIDEO_SUCCESS"



export const SET_PAGE = "SET_PAGE"
